# Generated by Django 3.2.7 on 2021-11-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardimage',
            options={'verbose_name_plural': 'CardImage'},
        ),
        migrations.AlterModelOptions(
            name='usercarddata',
            options={'verbose_name_plural': 'UserCardData'},
        ),
    ]
