# Generated by Django 3.2.7 on 2021-11-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_card', '0002_auto_20211108_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercarddata',
            name='card_image',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='usercarddata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_card.usercarddata'),
        ),
    ]
