# Generated by Django 3.2.7 on 2021-11-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_card', '0003_auto_20211108_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='usercarddata',
        ),
        migrations.AddField(
            model_name='usercarddata',
            name='usercarddata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_card.cardimage'),
        ),
    ]
